#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
data=$(mktemp -t ut71dmm.XXXX)
echo $data

sudo true

sleep 3 && gnuplot -e "data='\"$data\"'" -e "filter_awk='\"$DIR/filter.awk\"'" "$DIR/live.gpi" &

sudo "$DIR/../ut71dmm" > "$data"
